### PR TITLE
Laravel 7 support

### PR DESCRIPTION
**Pull request by giannidhooge**
### Changes

Please describe both what is changing and why this is important. Include:

- Upgrade dependencies

### References

Please include relevant links supporting this change such as a:

- https://laravel.com/docs/7.x/upgrade

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

[x] This change has been tested on the latest version Laravel

### Checklist

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

### CODE REVIEW

**Comment by giannidhooge** [comment]
@joshcanhelp please take a look when you have a spare moment

**Comment by giannidhooge** [comment]
@joshcanhelp  Any idea when `5.4.0` will be tagged? The `master` is also not yet available: https://packagist.org/packages/auth0/login#dev-master

**Comment by joshcanhelp** [comment]
@giannidhooge - Let me test out #166 and, if that looks good, we'll get this and that out at the same time. Master is now up-to-date on Composer 👍

**Comment by giannidhooge** [comment]
@joshcanhelp Seems like #166 is taking longer than expected. Perhaps you can already tag a release without it?

**Pull request merged**
