### PR TITLE
Fix cachehandler resolving issues

### PR DESCRIPTION
**Pull request by deviouspk**
This PR fixes the cachehandler to always return null

### CODE REVIEW

**Comment by deviouspk** [comment]
Noproblem!
Would you mind publishing a new patch release for this? This was a pretty serious flaw that comes with performance penalties in production environments.

**Comment by joshcanhelp** [comment]
@deviouspk - Absolutely. We're about due for one anyways. I'll push it out tomorrow morning 👍

**Comment by joshcanhelp** [comment]
@deviouspk - I have the release up on GitHub but Packagist removed a legacy package update method we were using. We're working to get the package moved under our official user there but, hopefully, the release here will help. I'll stay on it and ping this thread when it's live there. Thanks for your patience!

**Comment by joshcanhelp** [comment]
Update complete!

https://packagist.org/packages/auth0/login#5.2.0

**Comment by deviouspk** [comment]
thankyou!

**Pull request merged**
