### PR TITLE
Remove type declarations incompatible with laravel model

### PR DESCRIPTION
**Pull request by squpshift**
### Changes

Remove type declarations incompatible with laravel model

Examples of errors fixed in this PR:

https://flareapp.io/share/B5ZG4pNm
https://flareapp.io/share/W7zQNWbP

### References

These issues were raised in issue https://github.com/auth0/laravel-auth0/issues/413

### CODE REVIEW

**Comment by evansims** [comment]
Hi @squpshift 👋 Thanks for your suggestion. I'll evaluate these changes this week and get back to you.

**Comment by dylmye** [comment]
Hey I would appreciate an update on this if possible pretty please :)

**Comment by evansims** [comment]
👋 Appreciate your suggestion here. I'm unable to accept this pull request for a few reasons. First, the changes suggested would be a breaking change for existing applications that may already be extending these interfaces.

I'm also concerned that the content of the pull request represents a larger subset of changes than are necessary for compatibility with the Eloquent model class. If you review [the Eloquent model class](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Model.php), the only changes that should be necessary for compatibility lie in the `_get()` and `_set()` methods type hinting. However, changes to other methods are proposed by this pull request that are not exposed by the Eloquent model interface at all.

We're going to take a slightly different approach here and instead offer a new and separate abstract user model class specifically designed for use with Eloquent that applications can extend, without imposing a breaking change on existing integrations. We'll be releasing that within the next week or so. Again, thank you again for your suggestions here, we do genuinely appreciate your contribution and time.

**Comment by jacob-gardiner** [comment]
@evansims Is there any update on when the alternate approach mentioned above is going to be available? This issue does not appear to be fixed.

**Comment by evansims** [comment]
@jacob-gardiner Please open a new ticket describing your issue.

**Pull request closed without merging**
