### PR TITLE
AutoDiscovery

### PR DESCRIPTION
**Pull request by m1guelpf**
This will make the package work with [auto-discovery](https://github.com/laravel/framework/pull/19420) in Laravel 5.5.

Remember that you need to :label: a new version of the package after merging this!

### CODE REVIEW

**Comment by svenluijten** [comment]
Looks like it's missing a closing bracket for the `extra` object?

**Comment by m1guelpf** [comment]
@svenluijten Fixed, thank you!

**Comment by joshcanhelp** [comment]
@m1guelpf  - thanks for this! You said we need to "tag a new version," anything special about it or just a new tag? Want to make sure this gets out there correctly 👍

**Comment by m1guelpf** [comment]
@joshcanhelp You just have to tag it :smile:

**Pull request merged**
