### PR TITLE
Support Laravel 8

### PR DESCRIPTION
**Pull request by giannidhooge**
### Changes

Please describe both what is changing and why this is important. Include:

* Upgrade dependencies

### References

Please include relevant links supporting this change such as a:

- https://laravel.com/docs/8.x/upgrade
- Similar to #167 

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

[x] This change has been tested on the latest version Laravel

### Checklist

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

### CODE REVIEW

**Review by lbalmaceda — APPROVED** [review]
I'll add this to the CI as well. Thanks !

**Comment by lbalmaceda** [comment]
There are no official images for php8 yet, at least on CircleCI. I assume that is until PHP 8 reaches GA ([November 26th](https://wiki.php.net/todo/php80)). We won't be able to test this in the CI until then, but I'll reach out to the team to discuss this next release.

**Comment by giannidhooge** [comment]
@lbalmaceda Laravel 8 works on PHP ^7.3. No idea why we should wait until PHP8?

**Comment by lbalmaceda** [comment]
🤯🤯🤯 In my mind the PR was adding support for PHP 8. Disregard my comment then. Thanks

**Comment by giannidhooge** [comment]
@lbalmaceda No problem! Any idea when 6.1.0 will be tagged?

**Comment by lbalmaceda** [comment]
I'd expect this to be released sometime in the next ~7 days. We're tracking this release internally with the reference `SDK-1958`.

**Pull request merged**
