### PR TITLE
handle queryparam error coming from auth0 callback

### PR DESCRIPTION
**Pull request by afreakk**
Shouldnt you have something like this code addition in Auth0Controller, for handling errors coming in queryparam from auth0? 
Otherwise you get `null` from 
```
        $profile = $service->getUser();
```
And it will break further down somewhere.

### CODE REVIEW

**Comment by joshcanhelp** [comment]
Thanks for this @afreakk. This is something we have on our list internally so I'm glad to see an attempt here. 

I wonder, though, is it a little too heavy-handed to just end the process with a 500? Could we throw an exception or handle it some other way?

**Comment by afreakk** [comment]
Yeah i agree, but also, maybe it should be thrown inide auth0-php instead?  
Inside the `Auth0.php` `exchange` function, og maybe `getUser` function.

**Comment by joshcanhelp** [comment]
I'm not sure a thrown exception works here. The error code/description could be a hint to another action that could be taken (like `login_required` in the case where we're just checking for a session). Also, it's a little too generic of a parameter to assume that it came from Auth0 (I can imagine other apps using that error param and getting an exception when it wasn't related to an Auth0 callback). 

Let me think on this a bit and see if there is a better way to handle. Thanks for your thoughts here.

**Comment by afreakk** [comment]
yeah ill just close this then, and looking forward to a solution :)

**Pull request closed without merging**
